### ISSUE TITLE
Add option to manually indicate that a given application instance was upgraded to a new version

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#106]
Adding option to manually indicate in the Portal that a given application instance was upgraded to a new version (app version + chart version) in the background.

This feature should be only exposed to system administrators.

For a running application instance, administrator should be able to indicate (by triggering an action in the Portal) that it has been upgraded in manually in the background and that it's no longer in app version "A" but is actually in version "B".

The target version "B" should be selected from the list of available versions for given application (newer than version "A").

**Comment by llopat** [comment]
@kbeyro still verify:
- if proper label exists for the upgrade button
- do not use the standard condition check for upgrade possibility

**Comment by llopat** [comment]
@kbeyro 
this action should be restricted only to system administrators

**Comment by llopat** [comment]
@kbeyro only active versions should be listed for manual upgrade indication

![image](https://github.com/nmaas-platform/nmaas-platform/assets/21238476/1ac9b3ad-d6bb-42e1-bbd3-fc3c19327002)

**Comment by llopat** [comment]
After this is fixed. The ticket can be completed.

**Comment by llopat** [comment]
@kbeyro there is a bug with displaying available versions (the list is always empty)

**Comment by llopat** [comment]
@kbeyro still couple of improvements are requested:
- the current version should not be listed on the selector
- the option of manual upgrade should be visible on the Actions menu at all times but when opening the modal if there are no available versions a static text should be displayed instead of the selector saying: _No other versions available_
- when version is selected and upgrade is confirmed (and modal is closed) the current application instance details view should be refreshed so that the new version is displayed at the top

**Comment by llopat** [comment]
@korvoj could you retest this in QALAB1? The abovementioned changes were implemented.

**Comment by korvoj** [comment]
@llopat, the changes work as expected.
