### ISSUE TITLE
Enhance K8s client with collecting logs from pods

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#12]
The platform already contains a K8s client that facilitates a "shell-like" user access to particular pods that comprise the application instance deployed by a user (multiple pods might be deployed for a single application instance).

The current implementation has to be reviewed and enhanced in order to expose the "kubectl logs <pod>" command output over a new REST API endpoint.

**Comment by korvoj** [comment]
It would be best if this feature is configurable per app. For the virtual lab scenario, there might be some applications that should be used as "black boxes", e.g. during pen testing exercises. In such cases, the logs should not be exposed.

**Comment by llopat** [comment]
@korvoj you mean globally per application, per application in given domain or most granuarly per application instance?

**Comment by llopat** [comment]
Sounds good 👍

**Comment by llopat** [comment]
There are two issues encountered so far:
- reading logs from pod fails if there a multiple containers present on that pod (and it seems that "all containers" option in not supported by the client library)
- communication with the janitor fails if the size of logs is too big (hard to replicate currently)

**Comment by llopat** [comment]
@pgiertych in order to enable obtaining logs from particular container if a given pod has multiple containers we need to enhance the data model and related API request.
For the `/api/apps/logs//{appInstanceId}/pods` endpoint, the returned `PodInfo` object apart from `name` and `displayName` will also contain a list of `containers` (of type string). This list of `containers` can be either empty or container two or more container names.
In case of the `/api/apps/logs//{appInstanceId}/pods/{podName}` endpoint we should add and optional `{containerName}` path parameter or filter variable to be included only if given pod contains multiple containers. In such case, the API client is required to provide both `podName` and `containerName`.

**Comment by llopat** [comment]
@pgiertych the updated API works as expected however minor improvement in the UI would be required:
- the default container is not displayed in the selector (although the logs from this container are correctly requested from the backend)
- it would be beneficial to display a "loading" icon/visualization while the logs are being read from the backend (in might take some time if since the logs might grow very big)
- it would be preferable if the logs window would be automatically scrolled down to display the most recent logs
- in case the request for list of pods will return an empty list a static string saying "No logs are available for this application" should be displayed instead of the empty selectors

**Comment by llopat** [comment]
> There are two issues encountered so far:
> 
> * reading logs from pod fails if there a multiple containers present on that pod (and it seems that "all containers" option in not supported by the client library)
> * communication with the janitor fails if the size of logs is too big (hard to replicate currently)

There two issues are resolved by now. Only layout improvements are required.
