### ISSUE TITLE
Removal of an application prevents future imports

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#130]
When an application is removed from the catalog, future imports (using the JSON import functionality) of an application with the same base name and version are prevented. 

It should be possible to reimport an already deleted application.

**Comment by llopat** [comment]
@korvoj ok, currently we're only able to set application version status to DELETED (it's not entirely removed) and the application itself can't be currently removed. It's just not displayed when it has no "NOT DELETED" versions.

I suppose to support this case a new dedicated "delete" functionality should be implemented to remove respective entries from the database.

We should be able to remove given application version if the are not application instances based on this version and be able to remove the entire application if it doesn't have any versions.

**Comment by korvoj** [comment]
@llopat, just throwing out ideas here, would it be possible to bypass the uniqueness check in the database by appending "DELETED_$TIMESTAMP" to the column that has the unique constraint (e.g., chart name, app name...)?

**Comment by llopat** [comment]
@korvoj yeap, I think so, I wasn't sure if this is the case. This should be applied on the "app version" level only or on the "entire app" level as well?

**Comment by korvoj** [comment]
@llopat I would say on the app level, so that the import JSON functionality feature can be used multiple times "from scratch". Please correct me if I am wrong, but I think that feature imports a whole app, not a single version.

**Comment by llopat** [comment]
@korvoj you can do the imports from json file of the whole app or just a new version of an existing app.

So this is available on both levels.

**Comment by korvoj** [comment]
> So this is available on both levels.

> This should be applied on the "app version" level only or on the "entire app" level as well?

In that case I would say to have it applied on both levels, "app version" and "entire app".
