### ISSUE TITLE
Allow export of access method information for applications deployed in bulk

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#132]
When using the bulk application deployment functionality, it should be possible to export access information about the deployed applications using a CSV file.

The CSV file should contain the following information:

- username
- domain
- application name
- application instance name
- application version
- values of any customized parameters (each in a separate column)
- information about all supported access methods by the application (HTTP, SSH...)

**Comment by llopat** [comment]
Example CSV generated from a 3 Heathchecks instance bulk deployment:

`"domainCodeName","appName","appInstanceName","userName","appVersion","connection.healthchecks","url.healthchecks"
"pllab","Healthchecks","hc1-1","admin","2.1","healthchecks","hc1-1-pllab.public.nmaas.qalab.geant.net"
"pllab","Healthchecks","hc2-1","admin","2.1","healthchecks","hc2-1-pllab.public.nmaas.qalab.geant.net"
"pllab","Healthchecks","hc3-1","admin","2.1","healthchecks","hc3-1-pllab.public.nmaas.qalab.geant.net"
`

**Comment by llopat** [comment]
@kbeyro placement of this button should be improved



![Image](https://github.com/nmaas-platform/nmaas-platform/assets/21238476/6a0b7f59-354c-4ed5-bf57-c08bd30cf7a5)

**Comment by llopat** [comment]
`"domainCodeName","appName","appInstanceName","userName","appVersion","connection.postgresql","url.postgresql"
"pllab","PostgreSQL","ps1","llopat1","14.3.0","postgresql","pllab-postgresql-47"
`

**Comment by llopat** [comment]
Finally export looks ok (for a single instance in bulk)

`"domainCodeName","appName","appInstanceName","userName","appVersion","postgresql.service","postgresql.ip","param.global#postgresql#auth#database","param.global#postgresql#auth#postgresPassword","param.global#postgresql#auth#username","param.global#postgresql#auth#password"
"pllab","PostgreSQL","ps10","admin","14.3.0","pllab-postgresql-48","<EMPTY>","db1","pspass1","llopat1","pass1"
`

**Comment by llopat** [comment]
Still to add autogenerated parameters (like random passwords)
