### ISSUE TITLE
Handle namespace creation during domain provisioning

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#149]
An automatic way of creating the underlying Kubernetes namespace when a new domain is being provisioned needs to be implemented. For now this can be as simple as creating a namespace with the same name as the domain codename, but we should think how we can improve this in the future with support for executing arbitrary Ansible playbooks or externally defined workflows.

**Comment by korvoj** [comment]
No matter the adopted approach, the feature should support passing arbitrary annotations to the newly created namespace, e.g.:

```
...
metadata:
  annotations:
    cni.projectcalico.org/ipv4pools: '["customer-pool-ipv4"]'
    cni.projectcalico.org/ipv6pools: '["customer-pool-ipv6"]'
...
```

The values can either be hardcoded or determined based on the new domain created (e.g., the domain name)

**Comment by llopat** [comment]
@korvoj initially we're implementing a solution based on a simple K8S API call made by the Janitor (no use of yaml templates).
The whole namespace creation functionality can be enabled/disabled globally using a configuration property of the nmaas-platform. This property can be also set using a Helm value translated into environment variable passed to the platform.
Let's clarify. If enabled, this namespace creation should be triggered for both domains created manually and the ones created using bulk functionality, correct?
Currently we also added a dedicated property flag to indicate/control if a set of annotations should be included in the namespace creation request but now I think it might be redundant of those annotations should be added always.
Also regarding the annotations:
- do we foresee an option to pass custom annotation for bulk deployment in the csv file?
- do we foresee the need for the administrator to be able to define and update the set of default "global" annotations to be passed for every subsequent domain/namespace creation?
- administrator should be able to define/customise a set of annotation when defining new domain in the Portal, right?

**Comment by korvoj** [comment]
>  If enabled, this namespace creation should be triggered for both domains created manually and the ones created using bulk functionality, correct?

I would say yes.

>  if a set of annotations should be included in the namespace creation request but now I think it might be redundant of those annotations should be added always.
If there is an option for the administrator to edit the set of annotations from the portal, removing all "custom" annotations would achieve the same effect, no?

> do we foresee an option to pass custom annotation for bulk deployment in the csv file?
No, at least not at this point.

> do we foresee the need for the administrator to be able to define and update the set of default "global" annotations to be passed for every subsequent domain/namespace creation?
This would be a nice feature to have. Depending on the development effort, I would say that the initial implementation can be shipped without it, but it should be definitely be planned for a subsequent release.

> administrator should be able to define/customise a set of annotation when defining new domain in the Portal, right?
Yes, and the fields should be prefilled with the default "global" options, allowing the administrator to customize them on a case-by-case basis.

One question, is it currently possible to pass domain specific variables as the annotation values? For example to pass the domain name or the DCN networks as values to a "statically" set annotation key?

**Comment by llopat** [comment]
ok @kbeyro 
- we need a way to set, alter and persist list of "default/global" domain annotations to be maintained by administrator
- these global annotations will be added to each domain created in a bulk request
- these global annotations will be used to pre-populate the annotation specification view on the new domain creation view (to be further altered by the user if required before submitting the new domain request)
- we need a set of known annotation keys for which the values are provided automatically by the platform (e.g. client dcn networks or domain name) and apart from this we need to support defining custom/static annotations where both the key and the value is entered statically by the administrator

**Comment by llopat** [comment]
@korvoj could you please test the current implementation from your perspective?
The global domain namespace can be edit on a dedicated view accessible from the domain list view.
During manual domain creation the list of annotations is pre-populated with the global ones and can be altered as required.
For bulk domain creation the global annotations are applied.
Note that currently only purely static annotation values are supported. This will be enhances in the next release.

**Comment by korvoj** [comment]
@llopat , I would say the basic functionality works as expected. I tested the following
- editing the global annotations and deploying a new domain  without any manual edits on the domain view
- deploying a new domain with manual edits to the annotations on the domain view
- bulk domain deployment

However, I noticed the following
- annotations cannot be deleted in the global config view (an exception is thrown, please see QALAB1)
- the key field behaves a bit too aggressively and it automatically makes the input field "disabled" after pasting, without giving the user the option to edit the pasted value (this is not important, can be improved in subsequent release)
- most importantly, it seems that the following annotation cannot be added: `cni.projectcalico.org/ipv4pools: '["customer-pool-ipv4"]'`. I see the console message pasted below and the namespace is not created at all. Unfortunately passing such values that include `[]""` characters is necessary since that is how Calico's annotations work. 

```
Pattern attribute value [a-z0-9-]* is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[a-z0-9-]*/v: Invalid character class
```

**Comment by llopat** [comment]
ok, let's close this issue now and resume with a dedicated ticket regarding enhancements (e.g. dynamically assigned annotation values)
