### ISSUE TITLE
App instances with different names refer to the same domain address

### ISSUE THREAD

**Issue by marcinsiuda** [nmaas-platform/nmaas-platform#163]
In NMaaS we can create two instances of the application with similar names, for example "test" and "Test". The difference is only in the first letter (the name starts with an uppercase or lowercase). The problem is that both of them refer to the same address, for example https://test.domain.nmaas.eu/ even though these are two separate instances.

**Comment by llopat** [comment]
@marcinsiuda Fix will be released in version 1.6.0.
