### ISSUE TITLE
Enable generation of random deployment parameters as hex strings

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#164]
Currently application manager can specify that the value for particular Helm install parameter should be a automatically generated random string of specified length using the syntax `RANDOM_STRING_<length>`.

In some cases the generated sting should only contain digits and "hex" letters (a - f).
For such case a dedicated syntax should be used `RANDOM_HEX_<length>` in application specification and correctly processed by the platform.

**Comment by korvoj** [comment]
Maybe thus would be a good opportunity to also implement random numeric string generation, e.g. `RANDOM_NUMBER_<length>`. This might come in handy in the future, and I suppose it wouldn't be too much work to implement it together with `RANDOM_HEX`.
