### ISSUE TITLE
Introduce domain grouping

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#20]
In order to facilitate the virtual laboratory use case (but also to be applicable in other scenarios) a concept of a group of domains should be implemented.
The main goal of a group would be to enable the management of several independent domains from a single central point including:
- enabling/disabling of applications and configuration of application rules (e.g., time restrictions)

Assumptions:
- a single domain can be included in multiple groups (in this case restrictions defined on the group level should be combined on the domain level as a UNION)

Open questions that require further discussion:
- do we have to introduce a new dedicated role of a group administrator? (it might be considered to use the system administrator role for this purpose, anyway it seems that this role could be added at a later stage)

**Comment by llopat** [comment]
@korvoj please clarify:
- if given application is not enabled in any of the groups to which given domain belongs it should be hidden in the marked when given domain is selected, correct? (not disabled but hidden entirely)
- what should be the default state for applications within a new group (all enabled or all disabled)?

**Comment by korvoj** [comment]
@llopat ,

> if given application is not enabled in any of the groups to which given domain belongs it should be hidden in the marked when given domain is selected, correct? (not disabled but hidden entirely)

Yes, correct, it shouldn't be visible to the users of the given domain.

> what should be the default state for applications within a new group (all enabled or all disabled)?

The default state should preferably be "all disabled".

What would be the workflow for a brand new domain? Will there be a default group to which all new domains will be made part of so that users can have access to some basic set of applications?

**Comment by llopat** [comment]
@korvoj 
> What would be the workflow for a brand new domain? Will there be a default group to which all new domains will be made part of so that users can have access to some basic set of applications?

I would say that for a new domain created in a standard way no default group is applied and as it is done now all applications are enabled by default. Basically currently the same applies to a domain created in a bulk request.
As for now we don't have the notion of a default group(s). Also we assumed that if a domain belongs to one or more groups the application restrictions applied on the group level (merged as "union") entirely override the restrictions that might have been set on the domain level using the current functionality.

If a default group is desired, how this could be done in practice, e.g. one global default group applied to all domain or maybe possibility to indicate a default group for particular bulk domain creation (outside of the csv)?

**Comment by llopat** [comment]
@korvoj 

Do you have any further thoughts regarding this "default group" functionality or are you ok with the current approach I mentioned above?

**Comment by korvoj** [comment]
@llopat , the current approach looks sufficient for now, thanks.
