### ISSUE TITLE
Add new auth mechanism for new application version publishing

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#27]
We need to develop a new auth mechanism for automated app version publishing.

Currently used basic auth and JWT based security / access is not suitable mostly due to the fact that most of the users log in using eduGAIN (not local accounts).

Currently it seems that the best option would be to base the new security mechanism (for only a single endpoint or a couple) on a statically generated user tokens associated with user account.

As discussed this feature has low priority since as a workaround a dedicated "application manager" local account can be created for everyone willing to use this new application version publishing feature.

**Comment by llopat** [comment]
@korvoj 

Could you please provide your view on this feature and requirements from the "end user" (application manager) perspective?

**Comment by korvoj** [comment]
@llopat ,

This is the way I see it:
- independent of the login method of the user (either local login or via an IdP), it should be possible to create an authorization key/token that can only be used for accessing the API
- a given user can create multiple authorization tokens, each generated randomly by the Platform, and identified by a name given by the user during the creation process
- a token can be revoked by a user if they so choose, making it impossible to continue accessing the API using the revoked token (this is beneficial in case a token is compromised, e.g. posted publicly in a Git repository).
- a token can optionally have an expiry time, after which it will get invalidated/revoked automatically.
- there should be a dedicated view available somewhere in the profile page where the user can create/delete and preview currently available tokens.

If the Security framework allows, we might think about scoping such tokens in the future, e.g. allowing the user to specify what actions can be performed.
