### ISSUE TITLE
Allow viewing of randomly generated secrets during deployment time

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#36]
Users should be able to view the randomly generated secrets that have been generated for their application instance during deployment by the Platform. These secrets might include administrator passwords, database credentials, etc...

Perhaps it would be best if the feature is implemented in such a way as to allow any Helm parameter to be optionally visible by the user from the application access page. This would allow for statically configured parameters to be shown as well, e.g. for some charts we might decide to hardcore the username (e.g. `nmaas`), but use randomized values for the password. In such a case, both the username and the password should be visible in the access dialog.

**Comment by korvoj** [comment]
@llopat, I believe this issue can be merged with the one that we discussed over Slack regarding upgrading/viewing the configuration of a given instance.

**Comment by korvoj** [comment]
Coming back to this, the relevant excerpt from the conversation is:

> Vojdan: That's great, so it would be easy to implement View Configuration and Update Configuration. The first one would only show a read-only form of the values entered during deployment, while the second one would allow changing and would then do helm upgrade
> Lukasz: right, that's indeed doable, I think we might have had discussion that in such case it might be hard to keep the git repo in sync ...
> Vojdan: Ah, yes, but in this case it can be decided on a per-app basis

**Comment by llopat** [comment]
@korvoj currently we are able to display deployment parameters on the "Access" modal however those can't be filtered in anyway (yet).
Please advise if we could release this functionality already in 1.6.0 (without any filtering) and add relevant options to indicated which parameters should be exposed in 1.7.0 or turn this option off for 1.6.0?

It's just that we won't have time to do this still within 1.6.0.

**Comment by llopat** [comment]
Example:


![Image](https://github.com/nmaas-platform/nmaas-platform/assets/21238476/3735aa79-91ef-4e2f-8678-e1e2f4c3f899)

**Comment by korvoj** [comment]
@llopat , I would say to release it as is, and we can work on improvements in upcoming releases.
