### ISSUE TITLE
Implement prototype CSV file reader for bulk application deployment

### ISSUE THREAD

**Issue by kbeyro** [nmaas-platform/nmaas-platform#37]
As we plan to support bulk creation of domains and bulk deployment of application instances and since CSV is the desired input file format a suitable CSV parser needs to be developed.

Core implementation of the parser should be applicable for both domain creation and application deployment scenarios.
The following consideration originate mostly from application deployment use case.

The assumptions are as follows:
- requirements regarding the number, types and names of the CSV columns are listed below
- we can't assume a fixed structure of the CSV, some columns are mandatory and some are optional, in addition the position of given column (with given known name) shouldn't be taken for granted as well
- it was agreed that a single CSV allows for deployment of instances of only a single application hence a dedicated column with application name is not required within the CSV - this information (application name) will be passed independently from the CSV file

CSV column specification for application deployment use case:
- domain name [Required] - the name of the domain where the application needs to be deployed
- application instance name [Optional] - the name of the application instance. If not specified, a default name should be provided, for example the same as corresponding Helm release.
- application version [Optional] - the version of the application to be deployed. If not specified, the latest version available in the catalog is deployed.
- ...parameters [Optional] - list of extra (Helm) parameters, relevant to the application that needs to be deployed. Each parameter would be passed as a separate column in the CSV file, perhaps with some uniform prefix, which is to be defined.

**Comment by llopat** [comment]
Discussion related with requirement for this feature is conducted under https://github.com/nmaas-platform/nmaas-platform/issues/17
