### ISSUE TITLE
Implement new endpoint for bulk application deployment

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#40]
New dedicated controller should be added to expose a set of endpoints for application bulk lifecycle management.

Class should be added in the `/api/market` package. 
Suggested class name is `AppBulkController`. 
Root path: `/api/apps/bulks/`.

Following endpoints should be exposed (initially available only for System administrator users only):
- validating the bulk deployment request (provided application name and content of CSV file)
- triggering actual bulk deployment
- retrieving bulk deployment status (status of all application instances requested in bulk)
- undeploying bulk

**Comment by llopat** [comment]
@kbeyro I suppose we can close this issue, right? The related implementation continues in under a different issue.

**Comment by kbeyro** [comment]
@llopat yes, we can close this one

**Comment by llopat** [comment]
The basic functionalities in scope of this issue were implemented hence closing this .
