### ISSUE TITLE
Allow domain removal

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#71]
Users with the role "System admin" should be allowed to remove domains instead of just disabling them.

**Comment by korvoj** [comment]
@llopat ,

The main reason for requesting this feature was to remove domains that might never be used again. In the case of the virtual lab scenario, I expect that there will be many such domains over time (e.g., students that have graduated). In many cases universities even disable the accounts of such students, so even if they wanted to, they wouldn't be able to login into NMaaS if an IdP integration is in place. Taking this into account, the preference for the mentioned features is as follows:

> domain is no longer visible in the Portal (including the system administrator users)
Strongly preferred that the domain is no longer visible in the Portal. If you think that soft-delete is the way to go and simply mark the domain as deleted, without removing the entry itself from the database, this is fine. This might prevent new domains to be created with the same name, but in the context of the virtual lab use-case this might not be a problem. We might think whether a recreation of a new domain with a previously used name would be desired for other use-cases though. If yes, maybe we can just alter the domain name and add a suffix `-DELETED$TIMESTAMP`  `if there is a constraint on the domain name in the database.

> all users with roles assigned in a domain have those roles removed
Yes, this sounds acceptable.

> domain is entirely removed from the database (including application instances, no history, risky(?)) - new domains with the same codename can be created in the future
Tackled above, soft-delete is an option that might be worth exploring. The important thing is that in the case of the virtual lab scenario, yes, any active instances should be deleted as well. There should be a clear warning for this when an admin tries to remove a domain.

> k8s namespace removal script is triggered
Yes, this would be great.

> removal possible only if no application instances are running within the domain
Well actually as mentioned above it should be preferred if domains with active instances are deleted. There might be some stale instances no longer used by the domain owner, and it shouldn't be up to the administrator to find these manually and manually delete them before removing the domain.

> maybe removal only possible for domains created from bulk deployment ?
I think this would complicate things too much, and it might not be clear to other potential administrators why the feature is available in some cases and not in other.

Even with the soft-delete approach, it is not expected that a deleted domain will ever need to be reactivated. That's the function of the "disable" feature. So deletion is final in this case. The soft-delete approach in the database might be more suitable for debugging and accounting purposes.

**Comment by llopat** [comment]
@pgiertych 

We need to add a Flyway migration that would add the `boolean deleted` column to the `Domain` table

**Comment by llopat** [comment]
@llopat 

I will handle application instance removal from deleted domain

**Comment by llopat** [comment]
Still such constraint needs to be handled: External service domain is not unique (provided value: testd2.nmaas.qalab.geant.net)
