### ISSUE TITLE
Support out-of-band Helm chart upgrades

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-platform#76]
Currently the only way to update a running instance using NMaaS is to use the upgrade functionality which is only available between patch versions of the chart.

It should be possible to upgrade a chart on the command-line and let NMaaS know what is the new version of the app and the used chart, so that future patch updates to the chart itself can be tracked. This would allow complex upgrades between major versions to be done by the NMaaS team, while also allowing future patch updates to be done from the end-users using the Portal.

It should be possible only for a global administrator to manually edit the app/chart versions.

**Comment by korvoj** [comment]
@llopat , AFAIK this has been tackled by https://github.com/nmaas-platform/nmaas-platform/issues/106. Please verify and close this issue if needed.

**Comment by llopat** [comment]
@korvoj correct, closing now
